name = "vis_qwp"
configurations = [
    { idx = 1, name = "VAMP_MBI", value = { 1 = 8.05, 2 = 30.32 } },
]

[[devices]]
name = "1"
type = "elliptec-rotator"
unit = "deg"
offset = -47.6

[devices.serial]
port = "/dev/serial/by-id/usb-FTDI_FT230X_Basic_UART_DP06TV9W-if00-port0"
address = "1"

[[devices]]
name = "2"
type = "elliptec-rotator"
unit = "deg"
offset = 73.0

[devices.serial]
port = "/dev/serial/by-id/usb-FTDI_FT230X_Basic_UART_DP06TV9W-if00-port0"
address = "2"
