__all__ = ["VAMPIRES", "PYRO_KEYS", "VISWFS"]


class VAMPIRES:
    BS: str = "VAMPIRES_BS"
    CAMFCS: str = "VAMPIRES_CAMFCS"
    DIFF: str = "VAMPIRES_DIFF"
    FIELDSTOP: str = "VAMPIRES_FIELDSTOP"
    FILT: str = "VAMPIRES_FILT"
    FLC: str = "VAMPIRES_FLC"
    FOCUS: str = "VAMPIRES_FOCUS"
    MASK: str = "VAMPIRES_MASK"
    MBI: str = "VAMPIRES_MBI"
    PUPIL: str = "VAMPIRES_PUPIL"
    QWP1: str = "VAMPIRES_QWP1"
    QWP2: str = "VAMPIRES_QWP2"
    TC: str = "VAMPIRES_TC"
    TRIG: str = "VAMPIRES_TRIG"


class VISWFS:
    PICKOFFBS: str = "VISWFS_PICKOFFBS"
    CAMFCS: str = "VISWFS_CAMFCS"
    TROMBONE1: str = "VISWFS_TROMBONE1"
    TROMBONE2: str = "VISWFS_TROMBONE2"
    RS1: str = "VISWFS_RS1"
    RS2: str = "VISWFS_RS2"
    FLIPMOUNT1: str = "VISWFS_FLIPMOUNT1"
    FLIPMOUNT2: str = "VISWFS_FLIPMOUNT2"
    HWP: str = "VISWFS_HWP"


class PYRO_KEYS:
    VAMPIRES = VAMPIRES
    VISWFS = VISWFS
