__all__ = ["VAMPIRES", "PYRO_KEYS"]


class VAMPIRES:
    BS: str = "VAMPIRES_BS"
    CAMFCS: str = "VAMPIRES_CAMFCS"
    DIFF: str = "VAMPIRES_DIFF"
    FIELDSTOP: str = "VAMPIRES_FIELDSTOP"
    FILT: str = "VAMPIRES_FILT"
    FLC: str = "VAMPIRES_FLC"
    FOCUS: str = "VAMPIRES_FOCUS"
    MASK: str = "VAMPIRES_MASK"
    MBI: str = "VAMPIRES_MBI"
    QWP1: str = "VAMPIRES_QWP1"
    QWP2: str = "VAMPIRES_QWP2"
    TC: str = "VAMPIRES_TC"
    TRIG: str = "VAMPIRES_TRIG"


class PYRO_KEYS:
    VAMPIRES = VAMPIRES
