name = "vampires_fieldstop"
configurations = [
    { idx = 1, name = "Fieldstop", value = { x = 4.9502, y = 21.9037, f = 3.7961 } },
    { idx = 2, name = "CLC-2", value = { x = 7.705999, y = 2.8457, f = 3.696 } },
    { idx = 3, name = "CLC-3", value = { x = 8.022199, y = 9.474499, f = 3.6965 } },
    { idx = 4, name = "CLC-5", value = { x = 1.7915, y = 9.473899, f = 3.1963 } },
    { idx = 5, name = "CLC-7", value = { x = 1.4315, y = 2.8962, f = 4.495999 } },
    { idx = 6, name = "DGVVC", value = { x = 20.0784, y = 21.4782, f = 5.031199 } },
]

[[devices]]
name = "x"
type = "conex"
unit = "mm"
offset = 0

[devices.serial]
timeout = 0.5
port = "/dev/serial/by-id/usb-Newport_CONEX-AGP_A60MCHL5-if00-port0"
baudrate = 921600
xonxoff = true

[[devices]]
name = "y"
type = "conex"
unit = "mm"
offset = 0

[devices.serial]
timeout = 0.5
port = "/dev/serial/by-id/usb-Newport_CONEX-AGP_A60MCIFA-if00-port0"
baudrate = 921600
xonxoff = true

[[devices]]
name = "f"
type = "conex"
unit = "mm"
offset = 0

[devices.serial]
timeout = 0.5
port = "/dev/serial/by-id/usb-Newport_CONEX-AGP_A67H3XPH-if00-port0"
baudrate = 921600
xonxoff = true
