name = "vampires_mbi"
configurations = [
    { idx = 1, name = "Dichroics", value = 79.98048 },
    { idx = 2, name = "Mirror", value = 258.7218 },
    { idx = 3, name = "Pupil", value = 259.2013 },
]
unit = "deg"
offset = 0

[serial]
timeout = 0.5
port = "/dev/serial/by-id/usb-Newport_CONEX-AGP_A67H119F-if00-port0"
baudrate = 921600
xonxoff = true
