name = "vampires_mask"

[[configurations]]
idx = 1
name = "Open"

[configurations.value]
x = 7.799974875000001
y = 5.858017875000001
theta = 0.0004953764

[[configurations]]
idx = 2
name = "SAM-7"

[configurations.value]
x = 9.013126500000002
y = 8.443912500000001
theta = 26.90141

[[configurations]]
idx = 3
name = "SAM-9"

[configurations.value]
x = 8.37790425
y = 5.528833875
theta = 48.30059

[[configurations]]
idx = 4
name = "Open"

[configurations.value]
x = 8.358901874999999
y = 6.279975375
theta = 73.00045

[[configurations]]
idx = 5
name = "SAM-18"

[configurations.value]
x = 9.802891875
y = 5.0919697500000005
theta = 95.30249

[[configurations]]
idx = 6
name = "SAM-Ann"

[configurations.value]
x = 8.30199
y = 4.9120425
theta = 120.0005

[[configurations]]
idx = 7
name = "Mirror"

[configurations.value]
x = 9.252918375
y = 4.152947625
theta = 142.0003

[[configurations]]
idx = 8
name = "Open"

[configurations.value]
x = 10.106977500000001
y = 0.10001250000000002
theta = 164.0007

[[configurations]]
idx = 9
name = "LyotStop"

[configurations.value]
x = 8.49468075
y = 1.859803875
theta = 189.9104

[[configurations]]
idx = 10
name = "RAP"

[configurations.value]
x = 9.0569415
y = 7.858125
theta = 218.502

[[configurations]]
idx = 11
name = "ND10"

[configurations.value]
x = 8.048005875
y = 5.858017875000001
theta = 241.0004

[[configurations]]
idx = 12
name = "ND25"

[configurations.value]
x = 8.048005875
y = 5.858017875000001
theta = 265.0002

[[configurations]]
idx = 13
name = "LyotOpt"

[configurations.value]
x = 8.5079205
y = 3.3982818750000003
theta = 286.1818

[[configurations]]
idx = 14
name = "PupilRef"

[configurations.value]
x = 8.547925500000002
y = 4.058078625
theta = 310.6999

[[devices]]
name = "x"
type = "zaber"
unit = "mm"
offset = 0

[devices.serial]
timeout = 0.5
port = "/dev/serial/by-id/usb-FTDI_USB_Serial_Converter_FTG4YSH7-if00-port0"
device_number = 1

[[devices]]
name = "y"
type = "zaber"
unit = "mm"
offset = 0

[devices.serial]
timeout = 0.5
port = "/dev/serial/by-id/usb-FTDI_USB_Serial_Converter_FTG4YSH7-if00-port0"
device_number = 2

[[devices]]
name = "theta"
type = "conex"
unit = "mm"
offset = 0

[devices.serial]
timeout = 0.5
port = "/dev/serial/by-id/usb-Newport_CONEX-AGP_A6VRT271-if00-port0"
baudrate = 921600
xonxoff = true
