name = "vampires_mask"

[[configurations]]
idx = 1
name = "JEWEL4x5"

[configurations.value]
x = 10.360009125
y = 4.898040750000001
theta = 0.001783355

[[configurations]]
idx = 2
name = "SAM-7"

[configurations.value]
x = 10.193131125
y = 8.343757125
theta = 26.9033

[[configurations]]
idx = 3
name = "SAM-9"

[configurations.value]
x = 10.177986375
y = 5.188791375000001
theta = 48.30049

[[configurations]]
idx = 4
name = "JEWEL7x6"

[configurations.value]
x = 10.339006500000002
y = 5.719905375000001
theta = 73.00134

[[configurations]]
idx = 5
name = "SAM-18"

[configurations.value]
x = 10.382964375000002
y = 3.81180975
theta = 95.30318

[[configurations]]
idx = 6
name = "SAM-Ann"

[configurations.value]
x = 8.86206
y = 4.092082875
theta = 120.0005

[[configurations]]
idx = 7
name = "Mirror"

[configurations.value]
x = 9.252918375
y = 4.152947625
theta = 142.0003

[[configurations]]
idx = 8
name = "Open"

[configurations.value]
x = 9.106995375
y = 0.10001250000000002
theta = 164.001

[[configurations]]
idx = 9
name = "LyotStop"

[configurations.value]
x = 8.954595375
y = 1.13985675
theta = 189.7143

[[configurations]]
idx = 10
name = "RAP"

[configurations.value]
x = 9.376981500000001
y = 7.5580875
theta = 218.5039

[[configurations]]
idx = 11
name = "ND10"

[configurations.value]
x = 8.048005875
y = 5.858017875000001
theta = 241.0004

[[configurations]]
idx = 12
name = "ND25"

[configurations.value]
x = 8.048005875
y = 5.858017875000001
theta = 265.0002

[[configurations]]
idx = 13
name = "LyotOpt"

[configurations.value]
x = 8.5079205
y = 3.3982818750000003
theta = 286.1818

[[configurations]]
idx = 14
name = "PupilRef"

[configurations.value]
x = 8.547925500000002
y = 4.058078625
theta = 310.6999

[[devices]]
name = "x"
type = "zaber"
unit = "mm"
offset = 0

[devices.serial]
timeout = 0.5
port = "/dev/serial/by-id/usb-FTDI_USB_Serial_Converter_FTG4YSH7-if00-port0"
device_number = 1

[[devices]]
name = "y"
type = "zaber"
unit = "mm"
offset = 0

[devices.serial]
timeout = 0.5
port = "/dev/serial/by-id/usb-FTDI_USB_Serial_Converter_FTG4YSH7-if00-port0"
device_number = 2

[[devices]]
name = "theta"
type = "conex"
unit = "mm"
offset = 0

[devices.serial]
timeout = 0.5
port = "/dev/serial/by-id/usb-Newport_CONEX-AGP_A6VRT271-if00-port0"
baudrate = 921600
xonxoff = true
