name = "vampires_fieldstop"
configurations = [
    { idx = 1, name = "Fieldstop", value = { x = 4.770299, y = 21.8398, f = 4.75 } },
    { idx = 2, name = "CLC-2", value = { x = 7.936999, y = 3.2727, f = 4.7472 } },
    { idx = 3, name = "CLC-3", value = { x = 7.928199, y = 9.517299, f = 4.750099 } },
    { idx = 4, name = "CLC-5", value = { x = 1.6871, y = 9.514998, f = 4.75 } },
    { idx = 5, name = "CLC-7", value = { x = 1.6924, y = 3.2725, f = 4.75 } },
    { idx = 6, name = "DGVVC", value = { x = 20.3042, y = 21.8697, f = 5.234299 } },
]

[[devices]]
name = "x"
type = "conex"
unit = "mm"
offset = 0

[devices.serial]
timeout = 0.5
port = "/dev/serial/by-id/usb-Newport_CONEX-AGP_A60MCHL5-if00-port0"
baudrate = 921600
xonxoff = true

[[devices]]
name = "y"
type = "conex"
unit = "mm"
offset = 0

[devices.serial]
timeout = 0.5
port = "/dev/serial/by-id/usb-Newport_CONEX-AGP_A60MCIFA-if00-port0"
baudrate = 921600
xonxoff = true

[[devices]]
name = "f"
type = "conex"
unit = "mm"
offset = 0

[devices.serial]
timeout = 0.5
port = "/dev/serial/by-id/usb-Newport_CONEX-AGP_A67H3XPH-if00-port0"
baudrate = 921600
xonxoff = true
