name = "vampires_diffwheel"
configurations = [
    { idx = 1, name = "Open / Open", value = 0 },
    { idx = 2, name = "SII-Cont / SII", value = 60 },
    { idx = 3, name = "Ha-Cont / Halpha", value = 124.986735 },
    { idx = 4, name = "Open / Open", value = 180 },
    { idx = 5, name = "SII / SII-Cont", value = 240 },
    { idx = 6, name = "Halpha / Ha-Cont", value = 301.981037 },
    { idx = 7, name = "Block / Block", value = 31 },
]
unit = "deg"
offset = 0

[serial]
timeout = 0.5
port = "/dev/serial/by-id/usb-FTDI_USB-RS422_Cable_FT0B42PZ-if00-port0"
baudrate = 921600
xonxoff = true
