name = "vampires_flc"
configurations = [
    { idx = 1, name = "IN", value = 9.499996875 },
    { idx = 2, name = "OUT", value = 50 },
]
unit = "mm"
offset = 0

[serial]
timeout = 0.5
port = "/dev/serial/by-id/usb-FTDI_USB_Serial_Converter_FTG4YSH7-if00-port0"
device_number = 4
